### ISSUE TITLE
Missing serialVersionUID in class pascal.taie.util.collection.MapEntry

### ISSUE THREAD

**Issue by XYHyouka** [pascal-lab/Tai-e#10]
Class MapEntry implements the interface Serializable, but there's no field serialVersionUID defined in this class.
Field serialVersionUID can be automatically generated, but maybe different in different environment.
Does it design on purpose?

**Comment by zhangt2333** [comment]
It is a typo. 

Fixed in https://github.com/pascal-lab/Tai-e/commit/283d1ef5a4316232dc01fd7e454758e3ece88cfc.

Thanks.
