### ISSUE TITLE
When using methods such as Map.get(), if the return value is an array, the elements in the array will not be tainted.

### ISSUE THREAD

**Issue by springkill** [pascal-lab/Tai-e#102]
### Description

I used the following configuration:
```yml
  - { method: "<org.apache.catalina.connector.Request: java.util.Map getParameterMap()>", from: base, to: result }
```
When I use the return value of Map.get() directly as a sink, the taint is captured, but when I use the elements of the returned array, the taint is not added.
The reality is that the specific problem is:
When I was analysing the tomcat application, I needed to use the org.apache.catalina.connector.RequestFacade.getParameterMap() method, and the obtained ParameterMap was tainted with taints, and the array obtained by ParameterMap.get() also The array obtained by ParameterMap.get() is also tainted, but when I remove an element from the array, the taint disappears.
![image](https://github.com/pascal-lab/Tai-e/assets/118535366/453919b6-a1cb-4f22-aef4-a092f083d36c)
![image](https://github.com/pascal-lab/Tai-e/assets/118535366/cfb068d8-9202-4e8b-a560-1a469ae9f673)
![image](https://github.com/pascal-lab/Tai-e/assets/118535366/ae6717e4-f3ac-48bd-927e-8354225197e8)
I tried adding TRANSFER to the methods in the two images above, but still not getting the desired results.
```yml
  - { method: "<org.apache.catalina.connector.RequestFacade: java.util.Map getParameterMap()>", from: base, to: base.request }
  - { method: "<org.apache.catalina.connector.Request: java.lang.String[] getParameterValues(java.lang.String)>", from: base, to: "result[*]" }
```
Is there any way to fix this?

**Comment by zhangt2333** [comment]
> When I was analysing the tomcat application, I needed to use the org.apache.catalina.connector.RequestFacade.getParameterMap() method, and the obtained ParameterMap was tainted with taints, and the array obtained by ParameterMap.get() also The array obtained by ParameterMap.get() is also tainted, but when I remove an element from the array, the taint disappears.

I can't clearly understand what you're saying. And there are so many things circled in the chart that I don't know which to focus on. Would you be so kind as to illustrate with examples/current behavior/expected behavior?

**Comment by springkill** [comment]
The problem I'm trying to solve is, when the return value of the Map.get() method is an array, how do I mark the elements of the returned array with taints?
For example, how do I make the elements in the "values" array in the doPost() method carry tags?
```Java
package org.owasp.benchmark.testcode;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(value="/cmdi-00/BenchmarkTest00004")
public class BenchmarkTest00004 extends HttpServlet {
	
	private static final long serialVersionUID = 1L;
	
	@Override
	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doPost(request, response);
	}

	@Override
	public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
	
		java.util.Map<String,String[]> map = request.getParameterMap();
		String param = "";
		if (!map.isEmpty()) {
			String[] values = map.get("BenchmarkTest00004");
			if (values != null) param = values[0];
		}
		
		
		
		org.owasp.benchmark.helpers.ThingInterface thing = org.owasp.benchmark.helpers.ThingFactory.createThing();
		String bar = thing.doSomething(param);
		
		
		String cmd = "";
        String osName = System.getProperty("os.name");
        if (osName.indexOf("Windows") != -1) {
        	cmd = org.owasp.benchmark.helpers.Utils.getOSCommandString("echo");
        }
        
		Runtime r = Runtime.getRuntime();

		try {
			Process p = r.exec(cmd + bar);
			org.owasp.benchmark.helpers.Utils.printOSCommandResults(p, response);
		} catch (IOException e) {
			System.out.println("Problem executing cmdi - TestCase");
			response.getWriter().println(
			  org.owasp.esapi.ESAPI.encoder().encodeForHTML(e.getMessage())
			);
			return;
		}
	}
	
}
```

**Comment by zhangt2333** [comment]
I don't have your test environment and don't know how to reproduce your problem, in addition, you don't provide enough usable information (e.g. points-to-set, analysis options, complete analyzed program and complete `taint-config.yml`). All of the above makes it difficult for me to think, validate and answer your question.

Please offer the following infomation (otherwise, I don't know how to proceed.):
- The source code or Tai-e IR of `org.apache.catalina.connector.RequestFacade`, `org.apache.catalina.connector.Request`. (I don't even know what org.apache.catalina.connector.RequestFacade is and I'm not sure if what I searched for online is the same as yours either)
- The `pta-results.txt`, `tai-e-plan.yml`, `tai-e.log` in your `output` directory.
- any other helpful infomation.

**Comment by springkill** [comment]
Hi, it's been a long time since I received a reply, is this question still being followed?

**Comment by zhangt2333** [comment]
Sorry for the delay. Could you please share **your entire Tai-e project** with me, either via file upload or by providing a link to your GitHub repository? This will allow me to reproduce the issue with one-click.
