### ISSUE TITLE
Customize multiple entry methods

### ISSUE THREAD

**Issue by slimming-fat** [pascal-lab/Tai-e#112]
### Overall Description

How to specify multiple entry methods when constructing a call graph, is there an actual example, I am new to Tai-e.

### Expected Behavior

No

### Current Behavior

No

### Tai-e Arguments

<details>
  <summary>Click here to see Tai-e Options</summary>
  

  ```yaml
  {{The content of 'output/options.yml' file}}
  ```
</details>
<details>
  <summary>Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  {{The content of 'output/tai-e-plan.yml' file}}
  ```
</details>

### Tai-e Log

<details>
  <summary>Click here to see Tai-e Log</summary>
  

  ```
  {{The content of 'output/tai-e.log' file}}
  ```
</details>

**Comment by zhangt2333** [comment]
See https://github.com/pascal-lab/Tai-e/issues/9#issuecomment-1251836524

**Comment by slimming-fat** [comment]
Thank you very much. I'll try.

**Comment by zhangt2333** [comment]
I guess you want to dump the Call Graph in the disk.

To do this, use the following option: `"-a", "cg=dump-call-edges:true;"`

For more details, refer to the [Tai-e documentation on specific analysis options](https://tai-e.pascal-lab.net/docs/current/reference/en/command-line-options.html#specific-analysis-options). The relevant `cg` analysis option can be found in https://github.com/pascal-lab/Tai-e/blob/af7ae19ac4b5fb5f495bcd3aebe584775d7bfb6d/src/main/resources/tai-e-analyses.yml#L36-L44

**Comment by slimming-fat** [comment]
Yes, I have succeeded. Thank you very much for your patience.
