### ISSUE TITLE
Is there any way to be able to mock classes via tai-e at runtime.

### ISSUE THREAD

**Issue by Spr1n9T1me** [pascal-lab/Tai-e#114]
### Overall Description

I want to use tai-e to analyze the proxy behavior in java. For example,  following spring mybatis code:
~~~java
import org.apache.ibatis.annotations.Select;

public interface UserMapper {
    @Select("SELECT * FROM users WHERE id = #{id}")
    User selectUserById(int id);

    @Select("SELECT * FROM users")
    List<User> selectAllUsers();
}
~~~
Spring Framework uses JDK dynamic proxies to generate proxy implementation classes for these `Mapper` interfaces. These proxy classes implement the methods defined by the interfaces and perform the corresponding SQL operations. **Obviously, these implementation classes are generated at runtime and absent in source codes**, which makes it unable for tai-e to analyze the calling relationships here.

[Soot](https://github.com/soot-oss/soot) seems to be able to mock classes at runtime, such as the following code:
~~~java
        SootClass clazz = new SootClass("className");
        clazz.setResolvingLevel(SootClass.BODIES);
	clazz.setModifiers(Modifier.PUBLIC);
	clazz.addField(field)
        clazz.addField(sootField)
	clazz.setSuperclass(sootMethod);
	Scene.v().addClass(clazz)
~~~
So is there similar APIs in tai-e that makes it possible to **mock classes at  runtime.**

### Expected Behavior

none

### Current Behavior

none

### Tai-e Arguments

none

### Tai-e Log

none

### Additional Information

none

**Comment by zhangt2333** [comment]
Regarding mocking IR, Tai-e currently supports mocking IR within method at the statement level but does not support mocking an entire class. We will take this into consideration in the future.

In terms of semantic modeling, Tai-e offers support for both [mocking IR](https://github.com/pascal-lab/Tai-e/blob/af7ae19ac4b5fb5f495bcd3aebe584775d7bfb6d/src/main/java/pascal/taie/analysis/pta/plugin/util/IRModelPlugin.java) and [modeling side effects](https://github.com/pascal-lab/Tai-e/blob/af7ae19ac4b5fb5f495bcd3aebe584775d7bfb6d/src/main/java/pascal/taie/analysis/pta/plugin/util/AnalysisModelPlugin.java) (you can see their subclasses).

**Comment by Spr1n9T1me** [comment]
Appriciate your help! BTW, I noticed that the IR Mocking Model use [SignatureMatcher](https://github.com/pascal-lab/Tai-e/blob/af7ae19ac4b5fb5f495bcd3aebe584775d7bfb6d/src/main/java/pascal/taie/analysis/pta/plugin/util/AnalysisModelPlugin.java#L67) to match target methods, and I found [SignatureMatcherTest](https://github.com/pascal-lab/Tai-e/blob/af7ae19ac4b5fb5f495bcd3aebe584775d7bfb6d/src/test/java/pascal/taie/language/classes/SignatureMatcherTest.java) uses multiple kinds of regex,  is regular expression syntax **fully supported** in this Matcher?

**Comment by Spr1n9T1me** [comment]
Got it, thanks.
