### ISSUE TITLE
In the `onNewStmt method`, how to get the context?

### ISSUE THREAD

**Issue by YunFy26** [pascal-lab/Tai-e#117]
### 📝 Overall Description

Hello, I am using Tai-e's Plugin to process some stmts. In the `onNewStmt`method, I performed a new process on `LoadField`. 
```java
public void onNewStmt(Stmt stmt, JMethod container) {
        if(stmt instanceof LoadField loadField){
            JField field = loadField.getFieldRef().resolve();
            Collection<Annotation> annotations = field.getAnnotations();
            if (springUtils.isDependencyInjectionField(annotations)) {
                JClass jClass = springUtils.processInjectionField(loadField);
                if (jClass != null) {
                    Obj obj = heapModel.getMockObj(() -> "DependencyInjectionObj", field.getRef(), jClass.getType());
                    Var var = loadField.getLValue();
                    heapContext = contextSelector.selectHeapContext(container, obj);
                    solver.addVarPointsTo(context, var, heapContext, obj);
                }
            }
        }
    }
```
But the following two statements are incorrect
```java
heapContext = contextSelector.selectHeapContext(container, obj);
solver.addVarPointsTo(context, var, heapContext, obj);
```
Because in the parameters of `onNewStmt`, the type of `container` is `JMethod`, not `CSMethod`, I can't get the `context`

Please how can I solve this problem?

### 🎯 Expected Behavior

None

### 🐛 Current Behavior

None

### ⚙️ Tai-e Arguments

<details>
  <summary>🔍 Click here to see Tai-e Options</summary>
  

  ```yaml
  {{The content of 'output/options.yml' file}}
  ```
</details>
<details>
  <summary>🔍 Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  {{The content of 'output/tai-e-plan.yml' file}}
  ```
</details>

### 📜 Tai-e Log

<details>
  <summary>🔍 Click here to see Tai-e Log</summary>
  

  ```
  {{The content of 'output/tai-e.log' file}}
  ```
</details>

**Comment by zhangt2333** [comment]
`<pascal.taie.analysis.pta.plugin.Plugin: void onNewStmt(pascal.taie.ir.stmt.Stmt,pascal.taie.language.classes.JMethod)>` is a convenient version of `<pascal.taie.analysis.pta.plugin.Plugin: void onNewMethod(pascal.taie.language.classes.JMethod)>`+`jMethod.getIR().forEach(...)`.

What you may need is `<pascal.taie.analysis.pta.plugin.Plugin: void onNewCSMethod(pascal.taie.analysis.pta.core.cs.element.CSMethod)>`+`csMethod.getContext()`+`csMethod.getMethod().getIR().forEach(...)`.

**Comment by YunFy26** [comment]
Got it! Thank you.
