### ISSUE TITLE
There is a bug in the type checking of JClass when the application path does not specify a specific package name.

### ISSUE THREAD

**Issue by YunFy26** [pascal-lab/Tai-e#119]
### 📝 Overall Description

In `options.yml`
```
appClassPath: [project/BOOT-INF/classes]

#appClassPath: [project/BOOT-INF/classes/org/example/springtest]
```
The first configuration causes incorrect type checking. 

For example, there is an interface type
```java
package org.example.springtest;

public interface Injection {
    String sayInjection();
}
```
If the first appClassPath configuration is used, it will result in
```java
JClass aClass = World.get().getClassHierarchy().getClass("org.example.springtest.Injection");
aClass.isAbstract() == true;
aClass.isInterface() == true;
```

I have created a [repo](https://github.com/YunFy26/Tai-e_Tests) to reproduce this bug, please check it.

### 🎯 Expected Behavior

None

### 🐛 Current Behavior

None

### ⚙️ Tai-e Arguments

<details>
  <summary>🔍 Click here to see Tai-e Options</summary>
  

  ```yaml
  {{The content of 'output/options.yml' file}}
  ```
</details>
<details>
  <summary>🔍 Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  {{The content of 'output/tai-e-plan.yml' file}}
  ```
</details>

### 📜 Tai-e Log

<details>
  <summary>🔍 Click here to see Tai-e Log</summary>
  

  ```
  {{The content of 'output/tai-e.log' file}}
  ```
</details>

**Comment by zhangt2333** [comment]
> The first configuration causes incorrect type checking.

As stated in the [Java Language Specification, §9.1.1.1](https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.1.1.1), *Every interface is implicitly abstract*.

> `appClassPath: [project/BOOT-INF/classes/org/example/springtest]`

This is an incorrect class path in your case. It results in `World.get().getClassHierarchy().getClass("org.example.springtest.Injection")` retrieving a phantom class, whose modifiers may not be reliable.

**Comment by YunFy26** [comment]
Got it. Thanks!
