### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by FizzFish** [pascal-lab/Tai-e#13]
### Describe the bug

When running with "./gradlew test" in cmdline, I find that all testsuites FAILED.
Then I run a testsuite(testAssign) in IDEA, the output is
"Soot frontend failed to parse input Java source file(s).
This exception may be caused by:
1. syntax errors in the source code. In this case, please fix the errors.
2. language features introduced by Java 8+ in the source code.
   In this case, you could either compile the source code to bytecode (*.class)
   or rewrite the code by using old features."

The real problem is "Cannot invoke "soot.JastAddJ.ClassDecl.localMethodsSignature(String)" because the return value of "soot.JastAddJ.ClassDecl.superclass()" is null" in SootWorldBuilder.java. It's weird because the testsuite is right in Tai-e-assignments project.
Then I find that "lib/dependencies.jar" may contains Soot dependencies in Tai-e-assignments project, however Tai-e use soot.jar from gradle. I'm not sure it's the reason to make the difference. But how can I run the testsuites in Tai-e project ?

### Tai-e arguments

LiveVarTest.java
   public void testAssign() {
        testLV("Assign");
    }

### Runtime environment infomation

ubuntu 22
jdk-17.04
latest Tai-e, 0.0.3, 2022.10.26, commit c67eb3376f2b00370d7cb8d487439223d8ca8cd3

**Comment by FizzFish** [comment]
git submodule update --init --recursive
will resolve this problem.

**Comment by testmigrator** [comment]
> git submodule update --init --recursive will resolve this problem.

I also encountered the same problem, could you please tell me how to solve it in detail?
