### ISSUE TITLE
Taint Analysis

### ISSUE THREAD

**Issue by chennbnbnb** [pascal-lab/Tai-e#16]
### Clear and concise description of the problem

taint tracking is very useful in find Java vulns, So I advise to implement taint analysis in Tai-e

### Suggested solution

maybe IFDS framework?

**Comment by zhangt2333** [comment]
[Taint analysis](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/analysis/pta/plugin/taint/TaintAnalysis.java) has already been implemented.

See https://github.com/pascal-lab/Tai-e/wiki/Pointer-Analysis-Framework.

**Comment by chennbnbnb** [comment]
thanks, it's stupid question, I didn't notice that,
