### ISSUE TITLE
how to handle jar without main-class

### ISSUE THREAD

**Issue by chennbnbnb** [pascal-lab/Tai-e#17]
as I know, Tai-e need to specify entry class by option ``-m <main-class>``.
but for some jar library eg: jdk1.8, there isn't main class  to be specified, 
I wonder how to handler this case to carry out analysis

**Comment by chennbnbnb** [comment]
To be more specific, I want to carry out cg analysis on jdk1.8 through Tai-e framework. To compare this framework and flowdroid which one is better.
I'm new to static analysis, your response will help me a lot

**Comment by zhangt2333** [comment]
If you want to analyze JDK8, at least one method in your classes calls the method of JDK8 and this method is reachable from entry method(s).

Besides, `-m <main-class>` is not a required option. But it helps Tai-e to find a main method (`public static void main(String[] args)`) as entry method. If you need to specify some custom entry methods, see https://github.com/pascal-lab/Tai-e/issues/9#issuecomment-1251836524.

**Comment by chennbnbnb** [comment]
Hi, after many days of thinking, I believe analyzing java component which don't have explicate entry method  is diff from analyzing common java programs, this assignment need a new algorithm. it's not Tai-e's problem, so I will close this issue, thanks
