### ISSUE TITLE
why use TreeSet() to store TaintFlow instance?

### ISSUE THREAD

**Issue by chennbnbnb** [pascal-lab/Tai-e#20]
Hi, I notice this [code](https://github.com/pascal-lab/Tai-e/blob/febacef8750d25ffb15679b0ac25b744083804e7/src/main/java/pascal/taie/analysis/pta/plugin/taint/TaintAnalysis.java#L174) use `TreeSet` as container of `TaintFlow`.
`TreeSet` require `TaintFlow` must implement interface `Comparable`.

I wonder if it possible to replace `TreeSet` with `HashSet`, because element of `HashSet` doesn't have to be comparable.

**Comment by zhangt2333** [comment]
For a sorted result of `TaintFlow`s that helps dump and compare result.

**Comment by chennbnbnb** [comment]
thx
