### ISSUE TITLE
Request to enhance the input method of "--input-classes" parameter

### ISSUE THREAD

**Issue by Y4er** [pascal-lab/Tai-e#23]
### Clear and concise description of the problem

When I was using tai-e to analyze java web applications, I found that `--input-classes` was not able to meet the usage scenario.

In #19, I added a custom program entry point via onStart.

```java
package com.example.demo.controller;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;

@RestController
public class TestController {
    @RequestMapping("/")
    public String index(HttpServletRequest request) throws IOException {
        String cmd = request.getParameter("cmd");
        Runtime.getRuntime().exec(cmd);
        return "hello";
    }
}
```

and run with this args.

```
-cp
/Users/ddd/IdeaProjects/demo/target/classes/:/Users/ddd/IdeaProjects/demo/javax.servlet-api-4.0.1.jar
--input-classes=com.example.demo.HelloServlet,javax.servlet.http.HttpServletRequestWrapper
-java
8
-ap
-a
pta=action:dump;action-file:dumpfile;taint-config:src/test/resources/pta/taint/taint-config.yml
```

As a small demo this is fine, but in a real large java web application, the `-input-classes` parameter can cause some problems.

In the automated code audit, I need to add all the route endpoints to the entry point, and if I don't add the class names of the route endpoints and the class names of the parameters to the `--input-classes` collection, then neither the entry point nor the mock parameters can be added via `World.get().getClassHierarchy(). getClass(xx)` to get the corresponding class.

So it is requested to enhance this feature or give a more suitable way.

thanks.

### Suggested solution

I don't have any good ideas.

**Comment by silverbullettt** [comment]
Thank you for your info.

We did enhance `--input-classes` recently (in commit [0934e79](https://github.com/pascal-lab/Tai-e/commit/0934e7979547a2877c749a8fdc0b0c4dc709c30d)). Now it can accept `.txt` files as inputs, where you can list the class names to be added. In addition, we added a simple util class [ClassNameExtractor](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/util/ClassNameExtractor.java), which can extract all class names in the specified jar files, and its output can be directly taken as input by `--input-classes`. These updates may be helpful for you.

**Comment by Y4er** [comment]
thank you!
