### ISSUE TITLE
A question about the implementation of Taint Analysis

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#25]
Hello everyone. I am new to taint analysis. Documentation illustrates that the **taint analysis** in Tai-e is on the top of the **pointer analysis** framework. 
Q1: Does it mean that taint analysis cannot trace the data flow of **primitive** data type? 
Q2: Could I run it without specifying the sinks to propagate the taint as far as possible?
Thank you so much!

**Comment by silverbullettt** [comment]
Q1: Currently, yes. We may support tracing of primitive data in the future.
Q2: Yes. You could run the taint analysis without specifying sinks and just propagate the taints.

**Comment by anabioticsoul** [comment]
I get it. Thanks, that's helpful!

**Comment by anabioticsoul** [comment]
It seems that the taint analysis of Tai-e cannot handle the implicit flow which brings false negatives. As the basis of taint analysis, the pointer analysis is flow-insensitive and path insensitive.
```java
if(taintedVar == const0){
    a = 1;   //implicit assignment
}
```
Is **flow-sensitive** taint analysis required if I want to track the **primitive type** of data and **implicit flows**? Could you please recommend a relative algorithm or implementation? Thanks!

**Comment by silverbullettt** [comment]
Tracking primitive data is irrelevant to flow sensitivity. But handling implicit flow does require control-flow information. You could correlate conditional expression to the branches by using CFG and dominator algorithm provided by Tai-e.

ASAIK, [JSFlow](https://github.com/jsflow/jsflow) should be able to track implicit flow dynamically. It is for JavaScript, but may be useful for you as a reference.

**Comment by anabioticsoul** [comment]
Thank you so much! (๑•̀ㅂ•́)و
