### ISSUE TITLE
Is it possible to upgrade the soot dependency version?

### ISSUE THREAD

**Issue by struce2** [pascal-lab/Tai-e#28]
When I am using the dependency "org.soot-oss:soot:4.3.0-20211223.212205-256", WorldBuilder takes 10s+

<img width="875" alt="image" src="https://user-images.githubusercontent.com/17916470/216930391-6ea06efa-1c6d-4695-a6bf-f3e1d6a92af2.png">

When I upgraded to "org.soot-oss:soot:4.4.1", WorldBuilder only took 1-2s,
<img width="801" alt="image" src="https://user-images.githubusercontent.com/17916470/216930206-723171cb-9919-4ed9-8977-be47cf8e1111.png">

I'm not sure if this really has anything to do with the soot version.

**Comment by silverbullettt** [comment]
This looks nice. We will try to upgrade soot dependency.

**Comment by struce2** [comment]
This is my cmdline 
```
--input-classes=org.apache.jsp.bf6wgpw0qqyy9orw316ihzckb5xf7qo1,javax.servlet.http.HttpServletResponseWrapper,javax.servlet.http.HttpServletRequestWrapper
-java
8
-ap
-a
pta=action:dump;action-file:result;taint-config:src/test/resources/pta/taint/taint-config.yml;only-app:false;implicit-entries:false
-cp
/path/to/javax.servlet-api-4.0.1.jar:/path/to/jsp/compilerdir
```

1.jsp source code
```
<%
    Runtime.getRuntime().exec(request.getParameter("s"));
%>
```
I compiled this code with tomcat, you can download the attachment

[jsp.zip](https://github.com/pascal-lab/Tai-e/files/10703316/jsp.zip)

Here's some information about my environment, not sure if it's helpful

OS: macOS Monterey 12.6 
CPU: M1 Pro
Java Version: 
```
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
```

Today I retry again, the results are the same as I said before.

**Comment by silverbullettt** [comment]
Thank you for your information. We've tried more benchmarks and did observe the acceleration. We've upgraded soot and other dependency versions in commit [737b4b](https://github.com/pascal-lab/Tai-e/commit/737b4bd6e51ee376471d1ebe567a33bbb666571b). Thanks again.

**Comment by struce2** [comment]
Thanks for your work.
