### ISSUE TITLE
RuntimeException occurred during the initialization phase of analyzing hadoop

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#3]
Hello everyone, I've met a problem when I tried to analyze **hadoop** components (2.10.2). 
```
Exception in thread "main" java.lang.RuntimeException: couldn't find class: com.google.gson.internal.$Gson (are your class path and class name given properly?)
	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:249)
	at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:73)
	at pascal.taie.Main.lambda$buildWorld$3(Main.java:121)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.buildWorld(Main.java:116)
	at pascal.taie.Main.lambda$main$0(Main.java:55)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:48)
	at TestTaie.main(TestTaie.java:175)
```
The console logs says that I missed `com.google.gson.internal.$Gson`, but the release jar of Gson doesn't have this class. How can I get more detailed information? Could you please help me about that, thanks a lot!

**Comment by zhangt2333** [comment]
In general terms, the argument `-ap, --allow-phantom` can be set up (refer to [Tai-e's wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)#program-options)) to solve your problem if you don't care about why your class `com.google.gson.internal.$Gson` is not found.


Specifically, more information is required to be provided to reproduce and analyze this issue, such as:
* running arguments
* the program you analyze
* ... (additional helpful info)

**Comment by anabioticsoul** [comment]
> In general terms, the argument `-ap, --allow-phantom` can be set up (refer to [Tai-e's wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)#program-options)) to solve your problem if you don't care about why your class `com.google.gson.internal.$Gson` is not found.
> 
> Specifically, more information is required to be provided to reproduce and analyze this issue, such as:
> 
> * running arguments
> * the program you analyze
> * ... (additional helpful info)

Thanks for your reply! I successfully analyze hadoop but with many extra logs:
```
...
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$XAttrEditLogProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: void onChanged()>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: void onChanged()>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: void onChanged()>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$XAttrEditLogProto$Builder: void onBuilt()>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: void onBuilt()>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: void onBuilt()>
Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: void onBuilt()>
...
```
Can I ignore them?

**Comment by anabioticsoul** [comment]
> Hello everyone, I've met a problem when I tried to analyze **hadoop** components (2.10.2).
> 
> ```
> Exception in thread "main" java.lang.RuntimeException: couldn't find class: com.google.gson.internal.$Gson (are your class path and class name given properly?)
> 	at pascal.taie.frontend.soot.SootWorldBuilder.runSoot(SootWorldBuilder.java:249)
> 	at pascal.taie.frontend.soot.SootWorldBuilder.build(SootWorldBuilder.java:73)
> 	at pascal.taie.Main.lambda$buildWorld$3(Main.java:121)
> 	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
> 	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
> 	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
> 	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
> 	at pascal.taie.Main.buildWorld(Main.java:116)
> 	at pascal.taie.Main.lambda$main$0(Main.java:55)
> 	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
> 	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
> 	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
> 	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
> 	at pascal.taie.Main.main(Main.java:48)
> 	at TestTaie.main(TestTaie.java:175)
> ```
> 
> The console logs says that I missed `com.google.gson.internal.$Gson`, but the release jar of Gson doesn't have this class. How can I get more detailed information? Could you please help me about that, thanks a lot!

I finally resolve that Exception through changing the version of `gson`  to an older one, but it led to another RunTimeException. I think adding `-ap` option may be a good solution.

**Comment by zhangt2333** [comment]
> Thanks for your reply! I successfully analyze hadoop but with many extra logs:
> 
> ```
> ...
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$XAttrEditLogProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: void onChanged()>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: void onChanged()>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: void onChanged()>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$XAttrEditLogProto$Builder: void onBuilt()>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: void onBuilt()>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: void onBuilt()>
> Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: void onBuilt()>
> ...
> ```
> 
> Does these problems matter or maybe I can ignore them?

If you don't care that unresolved classes/methods (and the classes/methods they depend on) can't be analyzed, you can ignore them.

Otherwise, you need to make sure that the argument `classpath` you set up actually contains these classes.

**Comment by anabioticsoul** [comment]
> > Thanks for your reply! I successfully analyze hadoop but with many extra logs:
> > ```
> > ...
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$XAttrEditLogProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: void onChanged()>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: void onChanged()>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: void onChanged()>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: com.google.protobuf.UninitializedMessageException newUninitializedMessageException(com.google.protobuf.Message)>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$XAttrEditLogProto$Builder: void onBuilt()>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.EditLogProtos$AclEditLogProto$Builder: void onBuilt()>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.XAttrProtos$XAttrProto$Builder: void onBuilt()>
> > Failed to resolve <org.apache.hadoop.hdfs.protocol.proto.AclProtos$AclEntryProto$Builder: void onBuilt()>
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does these problems matter or maybe I can ignore them?
> 
> If you don't care that unresolved classes/methods (and the classes/methods they depend on) can't be analyzed, you can ignore them.
> 
> Otherwise, you need to make sure that the argument `classpath` you set up actually contains these classes.

Ok, that's helpful, thank you again! I'll close this issue.

**Comment by djaekim** [comment]
> > What if the classpath I setup indeed contains these classes, yet still complains "failed to resolve"?
> 
> The front-end builds the **World (the program being analyzed)** via reference analysis starting from the `--input-classes` or `--main-class`. There are some classes which are loaded by dynamic class loading, e.g., `Class.forName("org.package.MyClass")`. So they will not be in the World, then cause `failed to resolve`.
> 
> A workaround to avoid this situation is to put all classes in the classpath into `--input-classes`.

Thank you so much for quick reply. However, for my case, methods that are from inheritance, see below:

https://github.com/apache/dubbo/blob/2cd701cc1e0a12c211566629a613fa4722ec989e/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java#L62

I guess these are also due to dynamic loading, so I would get errors like 
`Failed to resolve <org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance getLoadBalance(java.lang.String)>`

So, I would have to also include  `dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java` this in the `input-classes`. However, I still obtain:  

`Failed to resolve <org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance getLoadBalance(java.lang.String)>`

My second question is, 
for scenarios like https://github.com/apache/dubbo/blob/2cd701cc1e0a12c211566629a613fa4722ec989e/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java#L62. 

The ICFG nodes will look like 
```
%stringconst0 = "consistenthash" :: [NormalEdge{$r19 = (org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest) %this -> %stringconst0 = "consistenthash"}]

<dubbo-cluster.target.test-classes.org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: void testNormalWhenRouterEnabled()>[2@L52] $r1 = invokevirtual $r19.getLoadBalance(%stringconst0) 
```

 Is there a way to get information about the reference to the source class? For example, getLoadBalance comes from LoadBalanceBaseTest.java and ConsistentHashLoadBalance.NAME comes from ConsistentHashLoadBalance.java

Thank you again for all the quick help I am getting.

**Comment by zhangt2333** [comment]
> So, I would have to also include `dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java` this in the `input-classes`. However, I still obtain:
> 
> `Failed to resolve <org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance getLoadBalance(java.lang.String)>`

More information is required to be provided to reproduce and analyze this issue, such as:

* running arguments
* the program you analyze
* a reproducible minimal example
* ... (additional helpful info)

> My second question is, for scenarios like https://github.com/apache/dubbo/blob/2cd701cc1e0a12c211566629a613fa4722ec989e/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java#L62.
> 
> The ICFG nodes will look like
> 
> ```
> %stringconst0 = "consistenthash" :: [NormalEdge{$r19 = (org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest) %this -> %stringconst0 = "consistenthash"}]
> 
> <dubbo-cluster.target.test-classes.org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: void testNormalWhenRouterEnabled()>[2@L52] $r1 = invokevirtual $r19.getLoadBalance(%stringconst0) 
> ```
> 
> Is there a way to get information about the reference to the source class? For example, getLoadBalance comes from LoadBalanceBaseTest.java and ConsistentHashLoadBalance.NAME comes from ConsistentHashLoadBalance.java
> 
> Thank you again for all the quick help I am getting.

`getLoadBalance` can be gotten by `JMethod::getDeclaringClass`. You can modify the dumper of ICFG to dump what you want. See https://github.com/pascal-lab/Tai-e/blob/283d1ef5a4316232dc01fd7e454758e3ece88cfc/src/main/java/pascal/taie/util/graph/DotDumper.java#L139-L142

There seems to be no direct way to know the source pointer of StringLiteral. I looked at the bytecode or Tai-e IR and they all assign literal to local variables, e.g., `ldc #1` in bytecode or `%stringconst0 = "consistenthash"` in Tai-e IR.

**Comment by djaekim** [comment]
> > So, I would have to also include `dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java` this in the `input-classes`. However, I still obtain:
> > `Failed to resolve <org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance getLoadBalance(java.lang.String)>`
> 
> More information is required to be provided to reproduce and analyze this issue, such as:
> 
> * running arguments
> * the program you analyze
> * a reproducible minimal example
> * ... (additional helpful info)
> 
> > My second question is, for scenarios like https://github.com/apache/dubbo/blob/2cd701cc1e0a12c211566629a613fa4722ec989e/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java#L62.
> > The ICFG nodes will look like
> > ```
> > %stringconst0 = "consistenthash" :: [NormalEdge{$r19 = (org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest) %this -> %stringconst0 = "consistenthash"}]
> > 
> > <dubbo-cluster.target.test-classes.org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalanceTest: void testNormalWhenRouterEnabled()>[2@L52] $r1 = invokevirtual $r19.getLoadBalance(%stringconst0) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there a way to get information about the reference to the source class? For example, getLoadBalance comes from LoadBalanceBaseTest.java and ConsistentHashLoadBalance.NAME comes from ConsistentHashLoadBalance.java
> > Thank you again for all the quick help I am getting.
> 
> `getLoadBalance` can be gotten by `JMethod::getDeclaringClass`. You can modify the dumper of ICFG to dump what you want. See
> 
> https://github.com/pascal-lab/Tai-e/blob/283d1ef5a4316232dc01fd7e454758e3ece88cfc/src/main/java/pascal/taie/util/graph/DotDumper.java#L139-L142
> 
> There seems to be no direct way to know the source pointer of StringLiteral. I looked at the bytecode and Tai-e IR. They all assign literal to local variables, e.g., `ldc #1` in bytecode or `%stringconst0 = "consistenthash"` in Tai-e IR.

Unfortunately, it's not a JMethod, but a Stmt. So, I cannot call `JMethod::getDeclaringClass`

**Comment by zhangt2333** [comment]
> Hi, from my understanding, getContainingMethodOf returns the method where it is used, but not the original source. For example, `https://github.com/apache/dubbo/blob/2cd701cc1e0a12c211566629a613fa4722ec989e/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java#L62`, it will return `void testNormalWhenRouterEnabled() {` and it's declaringClass would be the `ConsistentHashLoadBalanceTest `, but not `LoadBalanceBaseTest`.

Sorry, I misunderstood your question.

I wrote a minimal example to reproduce your question, is this what you want?

<img width="1757" alt="image" src="https://user-images.githubusercontent.com/35210901/196441928-e8934f84-4748-42d1-8a9e-41af449a7fe8.png">

**Comment by djaekim** [comment]
Yes 

> > Hi, from my understanding, getContainingMethodOf returns the method where it is used, but not the original source. For example, `https://github.com/apache/dubbo/blob/2cd701cc1e0a12c211566629a613fa4722ec989e/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java#L62`, it will return `void testNormalWhenRouterEnabled() {` and it's declaringClass would be the `ConsistentHashLoadBalanceTest `, but not `LoadBalanceBaseTest`.
> 
> Sorry, I misunderstood your question.
> 
> I wrote a minimal example to reproduce your question, is this what you want?
> 
> <img alt="image" width="1757" src="https://user-images.githubusercontent.com/35210901/196441928-e8934f84-4748-42d1-8a9e-41af449a7fe8.png">

Yes, exactly! I am trying find all these declaring class that comes from superclass in inheritance relationship. I already have the inheritance hierarchy, and I was trying to use Tai-e to see if I could get these declaring class from ICFG. However, from earlier discussion, seems like the IR cannot get the source pointer of StringLiteral.

**Comment by zhangt2333** [comment]
> However, from earlier discussion, seems like the IR cannot get the source pointer of StringLiteral.

Yes, there is no literal source pointer even at the bytecode level.

**Comment by djaekim** [comment]
> > taining all literals and constant variables.
> 
> I am new to all these bytecode manipulation. Is there a way to do it with Tai-e? If not, do you know if there is another direction I can take?

**Comment by zhangt2333** [comment]
> I am new to bytecode manipulation. Is there a way to do it with Tai-e? If not, do you know if there is another direction I can take?

Maintaining all String Literals and constant variables, I mean, try to make a brute matching between them to find the source pointers of String Literals.

Just an unverified idea, and I'm not sure if it's possible. 

OK. The unrelated discussion under this issue should be ended.
