### ISSUE TITLE
Taint analysis results are separate from pointer analysis results

### ISSUE THREAD

**Issue by struce2** [pascal-lab/Tai-e#30]
### Clear and concise description of the problem

The result of pointer analysis is quite big, sometimes you need to open a big file just to view the result of taint analysis, which is not reasonable, and if output to console, it may cause IDE to crash or  stuck(I encountered this situation)

### Suggested solution

We can consider adding an option to output to the specified file, such as taint-file or taint-result, if the option is not specified, the behavior is the same as if the option is not specified

**Comment by silverbullettt** [comment]
How about we output taint analysis results to console as long as it is enabled? So even if points-to results are not dumped, you can view taint analysis results on the console.

**Comment by struce2** [comment]
I think it's a good idea.

**Comment by silverbullettt** [comment]
Done. Please check commit [3f1f27d](https://github.com/pascal-lab/Tai-e/commit/3f1f27dfa371e52ee01cbd4b9ad04966a0613021).

**Comment by struce2** [comment]
Nice, is worked, thank you.
