### ISSUE TITLE
User-friendliness when inputting illegal analysis options

### ISSUE THREAD

**Issue by addaddgo** [pascal-lab/Tai-e#33]
If the **options** for an analysis is blank on **tai-e-analyses.yml**, the **ObjectMapper** will set the **Analysis.config.options** as **Collections$EmptyMap**.  see **Planconfig.parseConfig**

I set options by CLI argument which overwrite the Analyssi.config.options managed by ConfigManager. see **ConfigManager.overwriteOptions**
 But the **options** is an **Collections$EmptyMap** which is fixed-size. Calling **putAll** on it throws UsuprotedOperationException.

```java
        List<AnalysisConfig> analysisConfigs = AnalysisConfig.parseConfigs(content); // EmptyMap
        ConfigManager manager = new ConfigManager(analysisConfigs); 
        AnalysisPlanner planner = new AnalysisPlanner(
                manager, options.getKeepResult());
        boolean reachableScope = options.getScope().equals(Scope.REACHABLE);
        if (!options.getAnalyses().isEmpty()) {
            // Analyses are specified by options
            List<PlanConfig> planConfigs = PlanConfig.readConfigs(options);
            manager.overwriteOptions(planConfigs); // overwrite
```

Maybe my java version (jdk 17) is not right, or maybe it's a bug.

**Comment by zhangt2333** [comment]
Could you provide the following information?
* Tai-e arguments (the arguments you set up that caused this bug)
* Runtime environment infomation (Provide your OS, IDE, and version/commit of Tai-e)

**Comment by addaddgo** [comment]
in tai-e-analyses.yml:
```yml
- description: the API collected from android.jar
  analysisClass: qingren.extractor.APIExtractor
  id: api-extractor
```
Tai-e arguments
```
-acp ...../android.jar -scope ALL -a "api-extractor=outPath:xxxxx"
```
I didn't set the main class. I think it is irrelevant to this problem.

Exception:
```Exception
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281)
	at pascal.taie.config.AnalysisOptions.update(AnalysisOptions.java:74)
	at pascal.taie.config.ConfigManager.lambda$overwriteOptions$0(ConfigManager.java:79)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at pascal.taie.config.ConfigManager.overwriteOptions(ConfigManager.java:77)
	at pascal.taie.Main.processConfigs(Main.java:84)
	at pascal.taie.Main.lambda$main$0(Main.java:51)
	at pascal.taie.util.Timer.lambda$runAndCount$0(Timer.java:112)
	at pascal.taie.util.Timer.runAndCount(Timer.java:93)
	at pascal.taie.util.Timer.runAndCount(Timer.java:111)
	at pascal.taie.util.Timer.runAndCount(Timer.java:107)
	at pascal.taie.Main.main(Main.java:49)
```
If  the **options** in tai-e-analyses is set, AbstarctMap shoulds be LinkedHashMap, if not, then it should be EmptyMap.

I think this is caused by the use of EmptyMap in the **fastxml** library to fill in the missing AnalysisCOnfig.options. Have to fill in options in plan.yml?

Runtime Environment:
OS: Ubuntu 22.04.1 LTS
IDE: IntelliJ IDEA 2022.2.2
commit: efbf256a358362e0ae7853ca053f9282be4ca70b

**Comment by zhangt2333** [comment]
According to [wiki](https://github.com/pascal-lab/Tai-e/wiki/Analysis-Management#5-options-optional-a-map-of-default-option-values), if your own Analysis has options, you need to define them in `src/main/resources/tai-e-analyses.yml`. It is not allowed to overwrite an option beyond the definition by runtime-specified values (You can think of it as another format/input checking).

That is to say, you need to change
```
- description: the API collected from android.jar
  analysisClass: qingren.extractor.APIExtractor
  id: api-extractor
```
to
```
- description: the API collected from android.jar
  analysisClass: qingren.extractor.APIExtractor
  id: api-extractor
  options:
    outPath: null
```

Besides, we will improve the exception info for this case.

**Comment by addaddgo** [comment]
Nice, is worked, thank you.

**Comment by zhangt2333** [comment]
Updated in https://github.com/pascal-lab/Tai-e/commit/64ee6059e1a0337c38f73c2892fe0f6465c692b4.
