### ISSUE TITLE
duplicate pointer flow propagation?

### ISSUE THREAD

**Issue by cobragege** [pascal-lab/Tai-e#34]
Hello, Is it possible to remove the following bolding statement? I thought the propagate function in the DefaultSolver will cover the final pointer flow stuff,

**addPointsTo(target, targetSet);**
```
  public void addPFGEdge(Pointer source, Pointer target, PointerFlowEdge.Kind kind,
                           Transfer transfer) {
        PointerFlowEdge edge = new PointerFlowEdge(kind, source, target, transfer);
        if (pointerFlowGraph.addEdge(edge)) {
            PointsToSet targetSet = transfer.apply(edge, getPointsToSetOf(source));
            if (!targetSet.isEmpty()) {
                addPointsTo(target, targetSet);
            }
        }
    }
```

**Comment by silverbullettt** [comment]
No. Tai-e's pointer analysis is derived from the algorithm we teach in our course. As shown in page 52 of [the slides](https://cs.nju.edu.cn/tiantan/software-analysis/PTA-FD.pdf), this operation is necessary to ensure that *every object pointed by source is also pointed by target*.
