### ISSUE TITLE
Replace the behavior of some variables in java with our design statements with Tai-e

### ISSUE THREAD

**Issue by ShiningChuang** [pascal-lab/Tai-e#36]
I have just been exposed to the knowledge of PL, and I may need to use this knowledge in my current work. I need to replace the behavior (statements) of some variables in java with my own design statements. for instance:

`A a = new A() -> A a = my_new A()`
`b = a.get() -> b = a.my_get()`
`a.write(c) -> a.my_write(c)`

How should I use the tai-e framework to accomplish this task?

What I'm thinking about now is whether we can use pointer analysis on 'a', locate the behavior of 'a' at the IR level, modify the IR statement, and then convert the modified IR statement back to the Java language according to some rules. Is this idea feasible? Or can we use other functions of tai-e to solve this problem more ingeniously?

Thanks a lot!

**Comment by silverbullettt** [comment]
Tai-e's IR is immutable, but you can intercept IR in pointer analysis.

To accomplish the task, you may modify [`DefaultSolver.addCSMethod()`](https://github.com/pascal-lab/Tai-e/blob/2cfded16f93bb4038ff9322cb892db1c73914a50/src/main/java/pascal/taie/analysis/pta/core/solver/DefaultSolver.java#L780) to intercept the result of `method.getIR().getStmts()` and replace it by your modified IR. In this way, the core pointer analysis solver (see class `StmtProcessor`) analyzes the modified IR, but other plugins still analyzes the original IR, so you may need to be careful.

**Comment by ShiningChuang** [comment]
In order to achieve my goal, I want to use tai-e as an analysis tool.
My current question is: how should I use tai-e to obtain the memory size of all variables in a java and on which line are they assigned, read and written? What tools of tai-e should I use or where to start to create my own analysis
Thanks a lot for your reply!

**Comment by silverbullettt** [comment]
> In order to achieve my goal, I want to use tai-e as an analysis tool. My current question is: how should I use tai-e to obtain the memory size of all variables in a java and on which line are they assigned, read and written? 

See [Stmt.java](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/ir/stmt/Stmt.java), which provides APIs to get variables read/written by each `Stmt` and its line number.

> What tools of tai-e should I use or where to start to create my own analysis Thanks a lot for your reply!

See [How to Develop A New Analysis on Tai‐e?](https://github.com/pascal-lab/Tai-e/wiki/How-to-Develop-A-New-Analysis-on-Tai%E2%80%90e%3F)
