### ISSUE TITLE
Questions about options `-cp`, `-acp` and `--input-classes`

### ISSUE THREAD

**Issue by PeteLing** [pascal-lab/Tai-e#38]
### Describe the bug

I have some questions about tai-e options.Btw I take this [repo](https://github.com/JoyChou93/java-sec-code.git) as testing repository.
Firstly I come across a Exception `Exception in thread "main" java.lang.RuntimeException: Main-class has no main method!` when using the argument `-ap -cp "/java-sec-code/target/java-sec-code-1.0.0.jar" -m org.joychou.Application -java 8 -a "pta=only-app:true;implicit-entries:false;taint-config:/Tai-e/src/main/resources/taint-config.yml;action:dump;action-file:result.txt"`. 

Then I use `/java-sec-code/target/classes` instead of jar file in `-cp` and the exception is gone but I found in the analysis `World.get().getClassHierarchy().applicationClasses()` only get the class `org.joychou.Application`.(the argument is `-ap -cp "/java-sec-code/target/classes" -m org.joychou.Application -java 8 -a "pta=only-app:true;implicit-entries:false;taint-config:/Tai-e/src/main/resources/taint-config.yml;action:dump;action-file:result.txt"`)

I got all the application class in `World.get().getClassHierarchy().applicationClasses()` when I use `-acp` in arguments(`-ap -acp "/java-sec-code/target/classes" -m org.joychou.Application -java 8 -a "pta=only-app:true;implicit-entries:false;taint-config:/Tai-e/src/main/resources/taint-config.yml;action:dump;action-file:result.txt"`)

When I think it should be done, I found the callgraph is incomplete. 
The java code `Runtime.getRuntime().exec(cmd);` in CommandExec method, `<java.lang.Runtime: java.lang.Process exec(java.lang.String)>` should be one of the callee in the caller `CommandExec`. I was searching the answer in issues and I think may be the reason is invokevirtual. Finally, I add `--input-classes java.lang.Runtime` in options and solve the problem.
The arguement in the end is `-ap -acp "/java-sec-code/target/classes" -m org.joychou.Application -java 8 --input-classes java.lang.Runtime -a "pta=only-app:true;implicit-entries:false;taint-config:/Tai-e/src/main/resources/taint-config.yml;action:dump;action-file:result.txt"`

Maybe I solved the problem I mentioned before but I am still confused about the options though I don't know if the question I asked is easy for those students who have the degree in static analysis.

**1. What's the difference when using `-acp`、`-cp` and `--input-classes`? Can it provide some explicit usage in tai-e document?**
**2. When the call is `invokevirtual`, the solution is add it in option `--input-classes` even if it can be translated to the right tir in tai-e?** 

I also have some other advice in the following
1. Can the master in tai-e build a communicative community? Maybe it is a convenient way using WeChat Group?
2. The project is updated frequently, maybe it is better to public the release message(new function or some options is changed).

Sincerely hope tai-e can become an awesome project in static analysis and play a bigger role in code security～

### Tai-e arguments

-ap -acp "/java-sec-code/target/classes" -m org.joychou.Application -java 8 --input-classes java.lang.Runtime -a "pta=only-app:true;implicit-entries:false;taint-config:/Tai-e/src/main/resources/taint-config.yml;action:dump;action-file:result.txt"

### Runtime environment infomation

tai-e commit: 2cfded16f93bb4038ff9322cb892db1c73914a50

**Comment by zhangt2333** [comment]
> 1. What's the difference when using -acp、-cp and --input-classes? Can it provide some explicit usage in tai-e document?

Here is an example to illustrate it.

Suppose I have a project:
  * it based on JDK8
  * it uses a third-party library, e.g., [Apache commons-lang3](https://mvnrepository.com/artifact/org.apache.commons/commons-lang3/3.12.0)
  * it contains the class `Main` which contains a `public static void main(String[] args)` method. In method `Main.main`, the reflection (to be more precise, the dynamic class loading) is used to load an class `EntryPoint` and call some methods of it. So there is no explicit reference to the class `EntryPoint` in the class `Main`.

What is the program _P_ we want to analyze? The _P_ contains the JDK classes being used, the common-lang3 classes being used, `Main`, `EntryPoint`, some dynamic classes (e.g., Proxy classes), native code, configuration files and so on.

The class paths `-cp, --class-path` will tell Tai-e how to locate the classes of _P_, e.g., `/home/jre8/rt.jar:/home/common-lang3.jar:/home/myclasses/` (These specify the paths to the JDK, third-party libraries, and application classes respectively). In addition we have to use `-m, --main-class` to specify the class containing the main method, i.e. class `Main`.

Then frontend of analyzer will construct a closed-world of _P_ starting from `Main` by reference analysis. The closed-world of _P_ may **ONLY** contains some JDK classes, some common-lang3 classes and `Main` (no`EntryPoint`, assuming no reflection is used. no proxy classes, and so on). In this case we may have to actively add the `EntryPoint` to the closed-world of _P_ by `--input-classes` (see the [Wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options))).

Okay, how about the many classes that need to be added to the closed-world of _P_, can I specify a special path to add all of them? To use `-acp, --app-class-path` (see the [Wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options))).

> 2. When the call is invokevirtual, the solution is add it in option --input-classes even if it can be translated to the right tir in tai-e?

I cannot clearly understand your question, can you give me an example.

> 1. I also have some other advice in the following
> 2. Can the master in tai-e build a communicative community? Maybe it is a convenient way using WeChat Group?
The project is updated frequently, maybe it is better to public the release message(new function or some options is changed).

Thanks for your suggestions. We will take them into consideration.

Besides, we will start the Software Engineering release cadence at the beginning of the next release (including the next one), i.e. we will clearly inform about new features, bug fixes and breaking changes.

**Comment by PeteLing** [comment]
Thank you for your reply.I have a clear understanding of the first question.I also want to know if the jar package can be specified by `-acp`? If I pack the application and third-party library into one jar, can it be analyze by set the option `-cp`?

About the second question. Take `Runtime.getRuntime().exec(cmd)` for example. I can see the IR in tir.
```
    @org.springframework.web.bind.annotation.GetMapping({"/runtime/exec"})
    public java.lang.String CommandExec(java.lang.String cmd) {
        java.lang.Runtime $r1;
        java.lang.String %stringconst0;
        [0@L31] invokestatic <org.joychou.controller.SourceSink: void sink(java.lang.String)>(cmd);
        [1@L32] $r1 = invokestatic <java.lang.Runtime: java.lang.Runtime getRuntime()>();
        [2@L32] invokevirtual $r1.<java.lang.Runtime: java.lang.Process exec(java.lang.String)>(cmd);
        [3@L33] %stringconst0 = "";
        [4@L33] return %stringconst0;
    }
```
By Intuitively looking the tir we can find that the `CommandExec` calls the `getRuntime` and `exec`, which it also should be in callgraph. But I debug and finally figure out that if I don't explicitly add  `java.lang.Runtime` in the closed-world by `--input-classes`.The callgraph is incomplete and can not find the callee `exec` in `CommandExec`.

**Comment by PeteLing** [comment]
Considering this problem from taint analysis, sometimes I don't need the corresponding third-party library to be added to the PTA analysis or I don't need to know what some object instances are(especially the source and sink method) , but just want to recognize the callgraph and know that the actual parameters of some invokevirtual function calls are carried taint obj.

As more and more rules are added in taint-config.yml, if we all need to add it to PTA through the option `--input-classes`, the analysis time may exceed the actual expectation.

**Comment by zhangt2333** [comment]
> I also want to know if the jar package can be specified by -acp? 

Of course (jar and dir are supported, see the [Wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options))).

> If I pack the application and third-party library into one jar, can it be analyze by set the option -cp?

If it is a shadowed Jar, the third-party library classes and application classes are packaged together, it is supported. Others (like jar-in-jar) are not supported.

> But I debug and finally figure out that if I don't explicitly add java.lang.Runtime in the closed-world by --input-classes.The callgraph is incomplete and can not find the callee exec in CommandExec.

You should change `...pta=only-app:true;...` to `...pta=only-app:false;...`. [`only-app:true`](https://github.com/pascal-lab/Tai-e/blob/2cfded16f9/src/main/resources/tai-e-analyses.yml#L6) means that the JDK code will not be analyzed.

**Comment by PeteLing** [comment]
> > I also want to know if the jar package can be specified by -acp?
> 
> Of course (jar and dir are supported, see the [Wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options))).
> 
> > If I pack the application and third-party library into one jar, can it be analyze by set the option -cp?
> 
> If it is a shadowed Jar, the third-party library classes and application classes are packaged together, it is supported. Others (like jar-in-jar) are not supported.
> 
> > But I debug and finally figure out that if I don't explicitly add java.lang.Runtime in the closed-world by --input-classes.The callgraph is incomplete and can not find the callee exec in CommandExec.
> 
> You should change `...pta=only-app:true;...` to `...pta=only-app:false;...`. [`only-app:true`](https://github.com/pascal-lab/Tai-e/blob/2cfded16f9/src/main/resources/tai-e-analyses.yml#L6) means that the JDK code will not be analyzed.

I think it is works and I have deep understanding about the options I used now. Thanks for your help~

**Comment by PeteLing** [comment]
> > 1. What's the difference when using -acp、-cp and --input-classes? Can it provide some explicit usage in tai-e document?
> 
> Here is an example to illustrate it.
> 
> Suppose I have a project:
> 
> * it is based on JDK8
> * it uses a third-party library, e.g., [Apache commons-lang3](https://mvnrepository.com/artifact/org.apache.commons/commons-lang3/3.12.0)
> * it contains the class `Main` which contains a `public static void main(String[] args)` method. In method `Main.main`, the reflection (to be more precise, the dynamic class loading) is used to load an class `EntryPoint` and call some methods of it. So there is no explicit reference to the class `EntryPoint` in the class `Main`.
> 
> What is the program _P_ we want to analyze? The _P_ contains the JDK classes being used, the common-lang3 classes being used, `Main`, `EntryPoint`, some dynamic classes (e.g., Proxy classes), native code, configuration files and so on.
> 
> The class paths `-cp, --class-path` will tell Tai-e how to locate the classes of _P_, e.g., `/home/jre8/rt.jar:/home/common-lang3.jar:/home/myclasses/` (These specify the paths to the JDK, third-party libraries, and application classes respectively). In addition we have to use `-m, --main-class` to specify the class containing the main method, i.e. class `Main`.
> 
> Then frontend of analyzer will construct a closed-world of _P_ starting from `Main` by reference analysis. The closed-world of _P_ may **ONLY** contains some JDK classes, some common-lang3 classes and `Main` (no`EntryPoint`, assuming no reflection is used. no proxy classes, and so on). In this case we may have to actively add the `EntryPoint` to the closed-world of _P_ by `--input-classes` (see the [Wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options))).
> 
> Okay, how about the many classes that need to be added to the closed-world of _P_, can I specify a special path to add all of them? To use `-acp, --app-class-path` (see the [Wiki](https://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options))).
> 
> > 2. When the call is invokevirtual, the solution is add it in option --input-classes even if it can be translated to the right tir in tai-e?
> 
> I cannot clearly understand your question, could you give me an example?
> 
> > 1. I also have some other advice in the following
> > 2. Can the master in tai-e build a communicative community? Maybe it is a convenient way using WeChat Group?
> >    The project is updated frequently, maybe it is better to public the release message(new function or some options is changed).
> 
> Thanks for your suggestions. We will take them into consideration.
> 
> Besides, we will start the Software Engineering release cadence at the beginning of the next release (including the next one), i.e. we will clearly inform about new features, bug fixes and breaking changes.

Sorry, I also don't know the concept about the `EntryPoint` and the `main class`(--main-class), what's the difference of then?
You said `In this case we may have to actively add the EntryPoint to the closed-world of P by --input-classes` before, is it we can use `--input-classes` to add EntryPoint, but it seems I fail to do it.
