### ISSUE TITLE
`propagate-types` option does not seem to be effective

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#42]
### Describe the bug

I used the `propagate-types` option in pointer analysis, but it doesn't seem to be effective. I set the following types for propagate-types:

- int
- long
- float
- null
- reference
However, according to the results, it seems that only **reference** is effective, while the other results are all empty. 

### Tai-e arguments

```
                "-cp", "./workspace/testJar1.jar",
                "-m", "TestCase15",
                "-a", "icfg",
                "-a", "mymethod",
                "-a", "pta=propagate-types:[int,long,float,null,reference];cs:1-call",
                "-a", "constraint",
                "-ap"
```

### Runtime environment infomation

OS: Win 11
IDE: Jetbrains IDEA
The version of Tai-e: latest (https://github.com/pascal-lab/Tai-e/commit/10a633fff58ede7d7f33340a690e8f01159018eb)

Thank you so much!

**Comment by silverbullettt** [comment]
This is a feature, not a bug :-)

The option `propatate-types` is used to open the channels (on PFG) for propagating values of specified types in pointer analysis. It does not add the values to the pointers of PFG.
Objects of reference type are added to the pointers by [DefaultSolver](https://github.com/pascal-lab/Tai-e/blob/37b20bf58b73234a41b088424cafba9476e64280/src/main/java/pascal/taie/analysis/pta/core/solver/DefaultSolver.java), and values of other types can be added by plugins, depending on your needs.
For example, [NullHandler](https://github.com/pascal-lab/Tai-e/blob/37b20bf58b73234a41b088424cafba9476e64280/src/main/java/pascal/taie/analysis/pta/plugin/NullHandler.java) and [NumberLiteralHandler](https://github.com/pascal-lab/Tai-e/blob/37b20bf58b73234a41b088424cafba9476e64280/src/main/java/pascal/taie/analysis/pta/plugin/NumberLiteralHandler.java) add `null` and numbers to the pointers. You could try to use them together with `propagate-types`.

**Comment by anabioticsoul** [comment]
I understand, thank you for the clarification!
