### ISSUE TITLE
how to distinguish the application code with lib

### ISSUE THREAD

**Issue by chengxinwei** [pascal-lab/Tai-e#44]
### Clear and concise description of the problem

2 questions
1. How to distinguish the application code of an application from the lib depends on. It is expected that only the application code needs to be analyzed during analysis, and the lib package should be ignored. Because there are hundreds of lib packages for the application, and the code in the lib package is not what we care about, so if we analysis the whole program is not necessary, we want to ignore the lib, thanks.

2. if assumption 1 is true, which is the lib can be ignored, and only the application code is analyzed. Then another issue will come, How to analyze the pointer propagation of the dependent lib package? For example, spring's transaction template, like code following code, ideally, the pt of var order should be propagate to the parameter of orderService.save(order);

```
Order oder = new Order();
return transactionTemplate. execute(status -> { 
      orderService.save(order);
});
```

### Suggested solution

I have also done some research on soot, I've seem Tai-e ignore method depends on sootClass.isApplicationClass(), and soot use -include pkg and -exclude pkg to identify the class is a application class or not, but tai-e framework looks like doesn't have any interface to modify this value, thank you.

**Comment by zhangt2333** [comment]
I'll go along with your questions one by one and then I'll give my opinion on the essence of the scenario:

* Q1: There is a simple but limited way to distinguish the analyzed program at "level/scope" (i.e., APP code and non-APP code (LIB code + JDK code)). That means passing the LIB via option `-cp`, the APP via option `-acp` and setting [`-a "pta=only-app:true;..."` ](https://github.com/pascal-lab/Tai-e/blob/92adc485e3/src/main/resources/tai-e-analyses.yml#L6) to make it necessary to analyse only the app code. For a more specific explanation, please take a look at https://github.com/pascal-lab/Tai-e/issues/38#issuecomment-1463309824

* Q2: In your code snippet, the closure `status -> { orderService.save(order); }` will be called inside the `transactionTemplate.execute`. In other words, to analyse pointer propagation from `order` to `parameter0` of `orderService.save`, the `transactionTemplate.execute` should be analyzed but not ignored. In addition to this, [Lambda Analysis](https://github.com/pascal-lab/Tai-e/blob/92adc485e319a5c108b7d711f557b9c7b69a9f43/src/main/java/pascal/taie/analysis/pta/PointerAnalysis.java#L138-L140) and [InvokeDynmaic Analysis](https://github.com/pascal-lab/Tai-e/blob/92adc485e3/src/main/resources/tai-e-analyses.yml#L17) may be required to be enabled.


IMO, you are faced with a trade-off between soundiness and efficiency of analysis more than a simple control of the analysed part of the program.

So, I suggest you try modifying Tai-e's source code to quickly try out a prototype that solves your issue. The control of should-be-analyzed/ignored program part is in:

https://github.com/pascal-lab/Tai-e/blob/92adc485e319a5c108b7d711f557b9c7b69a9f43/src/main/java/pascal/taie/analysis/pta/core/solver/DefaultSolver.java#L527-L530

Besides, how to divide the analyzed program at "level/scope" (APP&non-APP or APP&LIB&JDK), we are considering a general way to solve it.

**Comment by chengxinwei** [comment]
thank you for replying.

but I'm not sure where is wrong, I've tried the way you said before, but it's not helpful. the following information is my code and input, and the output as well.

arguments:  
`
-pp -m InterTaintTransfer -cp src/test/resources/pta/taint/:src/test/resources/pta/taint/commons-lang-2.6.jar --input-classes=InterTaintTransfer -a pta=cs:2-type;dump-ci:true;dump:true;only-app:true;implicit-entries:false;taint-config:src/test/resources/pta/taint/taint-config.yml; -a cg=dump:true
`
(BTW: for this parts, I've checked the code, --input-class and acp should be same in this case)


code:
```
import org.apache.commons.lang.StringUtils;

class InterTaintTransfer {

    public static void main(String[] args) {
        String t1 = SourceSink.source();
        String s = new String();
        s = StringUtils.defaultIfBlank(s, "blank");
        SourceSink.sink(transfer(t1, s));
    }

    static String transfer(String s1, String s2) {
        return s1.concat(s2);
    }
}

```

result dot:
```
digraph G {
  node [color=".3 .2 1.0",shape=box,style=filled];
  edge [];
  "0" [label="<SourceSink: java.lang.String source()>",];
  "1" [label="<java.lang.String: java.lang.String concat(java.lang.String)>",];
  "2" [label="<org.apache.commons.lang.StringUtils: boolean isBlank(java.lang.String)>",];
  "3" [label="<java.lang.String: void <clinit>()>",];
  "4" [label="<org.apache.commons.lang.StringUtils: java.lang.String defaultIfBlank(java.lang.String,java.lang.String)>",];
  "5" [label="<java.lang.String: char charAt(int)>",];
  "6" [label="<java.lang.String: void <init>()>",];
  "7" [label="<InterTaintTransfer: java.lang.String transfer(java.lang.String,java.lang.String)>",];
  "8" [label="<SourceSink: void sink(java.lang.String)>",];
  "9" [label="<InterTaintTransfer: void main(java.lang.String[])>",];
  "10" [label="<java.lang.Character: boolean isWhitespace(char)>",];
  "11" [label="<java.lang.String: int length()>",];
  "0" -> "6" [label="[1@L10] invokespecial $r0.<java.lang.String: void <init>()>();",];
  "2" -> "11" [label="[1@L233] $i0 = invokevirtual r0.<java.lang.String: int length()>();",];
  "2" -> "5" [label="[8@L237] $c1 = invokevirtual r0.<java.lang.String: char charAt(int)>(i2);",];
  "2" -> "10" [label="[9@L237] $z0 = invokestatic <java.lang.Character: boolean isWhitespace(char)>($c1);",];
  "4" -> "2" [label="[0@L5729] $z0 = invokestatic <org.apache.commons.lang.StringUtils: boolean isBlank(java.lang.String)>(r0);",];
  "7" -> "1" [label="[0@L13] $r2 = invokevirtual r0.<java.lang.String: java.lang.String concat(java.lang.String)>(r1);",];
  "9" -> "8" [label="[6@L9] invokestatic <SourceSink: void sink(java.lang.String)>($r3);",];
  "9" -> "6" [label="[2@L7] invokespecial $r1.<java.lang.String: void <init>()>();",];
  "9" -> "0" [label="[0@L6] $r0 = invokestatic <SourceSink: java.lang.String source()>();",];
  "9" -> "7" [label="[5@L9] $r3 = invokestatic <InterTaintTransfer: java.lang.String transfer(java.lang.String,java.lang.String)>($r0, $r2);",];
  "9" -> "4" [label="[4@L8] $r2 = invokestatic <org.apache.commons.lang.StringUtils: java.lang.String defaultIfBlank(java.lang.String,java.lang.String)>($r1, %stringconst0);",];
}

```

dot graph
![image](https://github.com/pascal-lab/Tai-e/assets/4637591/2aa32719-0f40-471f-bba4-750b61c4943e)
the red part is unexpected.

thank you!

**Comment by chengxinwei** [comment]
BTW, I have another question, I've tried input class, acp, and cp, but these three arguments will be merged to -cp args when request soot.Main. 

![image](https://github.com/pascal-lab/Tai-e/assets/4637591/110d0ef7-e0ad-49fc-b0bb-bec4f79289e0)

and the ignore method is depends on both only-app=true and soot.isApplication.
![image](https://github.com/pascal-lab/Tai-e/assets/4637591/a3d291b5-20c7-44db-8a54-adcebfc51394)

So, I'm also wondering, is it my Tai-e version outdated or is it a bug?

**Comment by zhangt2333** [comment]
> BTW, I have another question, I've tried input class, acp, and cp, but these three arguments will be merged to -cp args when request soot.Main.
> ...
> So, I'm also wondering, is it my Tai-e version outdated or is it a bug?

Sorry for my mistakes. In my response, it should be `(i.e., APP code (APP+LIB) and non-APP code (JDK))` but not `(i.e., APP code and non-APP code (LIB code + JDK code))`.

**Comment by zhangt2333** [comment]
> ...
> dot graph ![image](https://user-images.githubusercontent.com/4637591/252173473-2aa32719-0f40-471f-bba4-750b61c4943e.png) the red part is unexpected.

A nice and clear description. Try to modify Tai-e's source code to quickly try out a prototype that solves your issue:

```diff
    private boolean isIgnored(JMethod method) {
+       if ("<org.apache.commons.lang.StringUtils: boolean isBlank(java.lang.String)>".equals(
+                method.getSignature())) {
+           return true;
+       };
        return ignoredMethods.contains(method) ||
                onlyApp && !method.isApplication();
    }
```

**Comment by chengxinwei** [comment]
I see, got it, thank you.
