### ISSUE TITLE
Confusion about the frontend

### ISSUE THREAD

**Issue by Laughh** [pascal-lab/Tai-e#54]
Hi! I have some confusion when using Tai-e.

1. The frontend cannot generate IR from source code if it refers to some features introduced by Java 8, right? 
2. If I carry out PTA, I cannot get the real variable name from `Var` instance, but 
```
pta finishes, elapsed time: 0.19s
Tai-e finishes, elapsed time: 2.85s
r13
r0
$r12
$r0
$r3
%stringconst3
$r9
$r0
$r6
$r8
$r14
```
So is there any way to get the real variable name which is consitent with source code?

**Comment by zhangt2333** [comment]
To Q1: Yes, please see explaination inhttps://github.com/pascal-lab/Tai-e/wiki/How-to-Run-Tai%E2%80%90e%3F-(command%E2%80%90line-options)#program-options

To Q2: We could fetch the local variable table (including local variable name), but it is not trivial to map the name to `jimple` local variable converted&generated&manipulated by Soot

**Comment by Laughh** [comment]
Thanks a lot! But I still have two questions.

- Q1: Does it mean that Tai-e can analyze new classes introduced by Java 8+, but don't support the code writing, such as type inference?

- Q2: Does it mean that before Tai-e uses its own frontend, I can only get the variable name generated by Soot (like `$r1`), instead of the actual name appeared in source code?

**Comment by zhangt2333** [comment]
To Q1: I do not understand your question clearly. Type inference is performed at Jimple representation level.

To Q2: Yes for bytecode frontend, no for source code frontend.

**Comment by Laughh** [comment]
> 



>

**Comment by Laughh** [comment]
> To Q1: I do not understand your question clearly. Tai-e can analyze Java 17 bytecode currently. Type inference is performed at Jimple representation level.
> 
> To Q2: Yes for bytecode frontend, no for source code frontend.

I got it. Thanks a lot!
