### ISSUE TITLE
Method resolution is null

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#55]
I get exception here when analyzing some library:

https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/ir/proginfo/MethodRef.java#L184.

arguments are:
```
-pp
-ap
-scope
ALL
-a
pta=implicit-entries:false;only-app:false;handle-invokedynamic:true;cs:2-type;dump:false;reflection-inference:solar;handle-invokedynamic:true;merge-string-objects:false;distinguish-string-constants:all
-a
cg=dump-call-edges:true
```

The class  (defined as phantom) I get the exception on is not in classpath, so I thought the ```-ap``` should have handled this method resolution somehow.
Similar to what it does here:
https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/language/classes/ClassHierarchyImpl.java#L275

**Comment by zhangt2333** [comment]
Thanks for your issue.

There is indeed an inconsistency in phantom field and method processing here.

Just let you know we are working for this.

**Comment by michaelphop** [comment]
ok thanks

**Comment by silverbullettt** [comment]
Where did you encounter the exception? Is it thrown by Tai-e's code or your analysis?

**Comment by michaelphop** [comment]
The exception is thrown here:
https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/ir/proginfo/MethodRef.java#L184

The method I am trying to resolve if from my application code

**Comment by silverbullettt** [comment]
Thanks for your info. We will fix this issue in our new front end, but we may not fix it in current master branch, as it will cause conflicts later when we merge new front end. You could use `MethodRef.resolveNullable()`, which doesn't throw exception, and returns `null` instead.
