### ISSUE TITLE
NULL object reference

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#57]
When calling this function:
https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/analysis/pta/plugin/invokedynamic/InvokeDynamicAnalysis.java#L446

the ```recv``` is null.
 
And then, when:
https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/analysis/pta/plugin/invokedynamic/InvokeDynamicAnalysis.java#L415

is invoked, we get exception because ```recv=null``` and we do: ```recv.getObject().getType()```

**Comment by zhangt2333** [comment]
Any test case to reproduce this exception?

The comment points out that the `recv` is nullable:

https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/analysis/pta/plugin/invokedynamic/InvokeDynamicAnalysis.java#L405-L407

It looks like the author of the code is clear that `recv` should not be null when the `methodHandler` is kind of `invokeVirtual`:

https://github.com/pascal-lab/Tai-e/blob/24caba62a537184a85a5f768726783cbeafb940e/src/main/java/pascal/taie/analysis/pta/plugin/invokedynamic/InvokeDynamicAnalysis.java#L414-L415
