### ISSUE TITLE
JDK exclusion

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#58]
what is the purpose of this line?

https://github.com/pascal-lab/Tai-e/blob/7d53b98253ca417a8f28e6848ea8575cc7093d88/src/main/java/pascal/taie/frontend/soot/SootWorldBuilder.java#L100

Why only those two classes?

**Comment by zhangt2333** [comment]
> what is the purpose of this line?

It is same with https://github.com/pascal-lab/Tai-e/issues/48#issuecomment-1649740804.

> Why only those two classes?

Because [determineExcludedPackages](https://github.com/soot-oss/soot/blob/ddc7f3c6d0e68b4699ab3e23f6df36d7caea9979/src/main/java/soot/Scene.java#L201-L209) will handle the others.
