### ISSUE TITLE
Method call with reflection is not detected

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#59]
### Describe the bug

Consider the follwing code:

```java
public class Foo {
    void test() {
        System.out.println("called!");
    }
}

public class Main {

    public static void main(String... args) throws Throwable {
        Foo f = new Foo();
        Class<?> cl = f.getClass();
        Method m  = cl.getDeclaredMethod("test");
        m.invoke(f);
    }
}
```

In the output (```call-edges.txt```), I don't see call to ```Foo:test``` .

As opposed to: 
```java
Class<?> cl = Class.forName("Foo");
```
In this case, I do see the call to ```Foo:test``` .

Could be because ```getClass``` is native?

### Tai-e arguments

-pp
-ap
-scope
ALL
-a
pta=implicit-entries:true;only-app:false;cs:2-type;dump:false;reflection-inference:solar;handle-invokedynamic:true;merge-string-objects:true;distinguish-string-constants:all
-a
cg=dump-call-edges:true

**Comment by zhangt2333** [comment]
Thanks.

Fixed in https://github.com/pascal-lab/Tai-e/commit/b838dbe97d27e4d854871fde207380a9ec5958de.
