### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by enochii** [pascal-lab/Tai-e#6]
> Environment: Windows 10
> Idea: Community Version, 2022.2.1

When I try to set up Tai-e, I met some problems. It seems that the language feature(multi-line string, pattern matching for switch) are not supported, which confused me. Follow the instruction [here](https://github.com/pascal-lab/Tai-e/wiki/Setup-Tai%E2%80%90e-in-IntelliJ-IDEA), I can not find the Oracle openjdk17.

<img src=https://user-images.githubusercontent.com/33364190/190419924-8caacec9-3fea-4556-979a-e761bf6a41a4.png height=300>

So I use openjdk 18 instead. I also try the language level as 17(Preview), 18(no new) and 18(Preview), still has errors(see below).

<img src=https://user-images.githubusercontent.com/33364190/190426776-2ea141d1-fd7e-4129-abb8-2cec04980e2d.png height=250>

When I run the tests or `Main` class, it complains the below errors. Although the idea UI seems all right(i.e. no red line...).

<img src=https://user-images.githubusercontent.com/33364190/190420671-20550b89-90e3-4ef5-aa43-ef4384476eed.png height=500>
<img src=https://user-images.githubusercontent.com/33364190/190420750-db5a4826-0233-4f52-857e-c1019775a864.png height=700>

I new a demo project with pattern matching switch, use the openjdk18 and 18(Preview), the program works fine. With `17 - Sealed types, ...` as suggested, the idea UI has red lines, the error also suggest `--enable-preview`(but it is only supported in 18). Also the error here is quite different when setting up Tai-e.

![image](https://user-images.githubusercontent.com/33364190/190424824-0bc8da6b-64d9-4c84-9f27-71deb5879851.png)

This issue may be a little stupid... Any advide? Thanks for your time.

**Comment by zhangt2333** [comment]
I can't reproduce your issue.

Maybe you can try to `Invalidate Caches` and restart your IDE.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/35210901/190616054-a3836d27-bd52-4a12-9953-b0c6d5b63e4a.png">

**Comment by enochii** [comment]
> I can't reproduce your issue.
> 
> Maybe you can try to `Invalidate Caches` and restart your IDE.
> 
> <img alt="image" width="302" src="https://user-images.githubusercontent.com/35210901/190616054-a3836d27-bd52-4a12-9953-b0c6d5b63e4a.png">
Thanks for your response! `Invalidate Caches` seems doesn't work. 😂 I also encounter this issue in another laptop. Maybe I could try idea ultimate version later.

**Comment by zhangt2333** [comment]
@enochii 

Could you try the following actions ? (IDEA Ultimate Edition is better)
1. Delete `.gradle`, `build`, `.idea`, `buildSrc/.gradle` and `buildSrc/build`.
2. Restart IDEA.
3. In `Project Structure`, set the SDK to `Oracle OpenJdk 18`, set the Language level to `SDK default`.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/35210901/190957246-fc75f28a-8c6a-4b83-98f2-7cafb0b31e53.png">
4. Refresh Gradle.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/35210901/190957669-d8e261c7-d04a-4674-b5e5-65faa3821b42.png">

**Comment by enochii** [comment]
> @enochii
> 
> Could you try the following actions ? (IDEA Ultimate Edition is better)
> 
> 1. Delete `.gradle`, `build`, `.idea`, `buildSrc/.gradle` and `buildSrc/build`.
> 2. Restart IDEA.
> 3. In `Project Structure`, set the SDK to `Oracle OpenJdk 18`, set the Language level to `SDK default`.
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/35210901/190957246-fc75f28a-8c6a-4b83-98f2-7cafb0b31e53.png">
> 
> 4. Refresh Gradle.
> <img alt="image" width="250" src="https://user-images.githubusercontent.com/35210901/190957669-d8e261c7-d04a-4674-b5e5-65faa3821b42.png">

@zhangt2333 Thanks for your detailed response! I try the ultimate version, it works like a charm~

Though the community idea still get the same error. Also, in community version, when I execute `step 4 Refresh Gradle` , the previously set language level(i.e. `SDK Default`) will automatically change to `8(...)`. So I guess this set up issue may be related  to the community idea?

Thanks a lot! Have a nice day.
