### ISSUE TITLE
Phantom class creation

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#60]
In the following code:
https://github.com/pascal-lab/Tai-e/blob/b838dbe97d27e4d854871fde207380a9ec5958de/src/main/java/pascal/taie/frontend/soot/SootClassLoader.java#L57

Why do we pass ```false``` to ```getSootClassUnsafe```?
Doesn't it make more sense to pass ```true```? (That if jclass is null, let's create a new fake sootClass and mark it as phantom)

**Comment by silverbullettt** [comment]
We would like to make this API (`JClassLoader.loadClass(String)`) safer. If it passes `true`, then it may also create a phantom class even if it receives an arbitrary string.
