### ISSUE TITLE
Program doesn't end

### ISSUE THREAD

**Issue by runner02** [pascal-lab/Tai-e#61]
### Describe the bug

I run the following program:

```java
package org.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Main {

    public static void main(String[] args) {
        ApplicationContext context = new ClassPathXmlApplicationContext("Beans.xml");
    }
}
```

Also attached ```pom.xml``` dependencies section:
```xml
 <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <version>3.1.2</version>
        </dependency>
    </dependencies>
```

and it never ends although there is only one call

### Tai-e arguments

-cp
MyApp.jar:/home/runner/.m2/repository/org/springframework/spring-beans/6.0.11/spring-beans-6.0.11.jar:/home/runner/.m2/repository/org/springframework/spring-context/6.0.11/spring-context-6.0.11.jar:/home/runner/.m2/repository/org/springframework/spring-core/6.0.11/spring-core-6.0.11.jar:/home/runner/.m2/repository/org/springframework/spring-jcl/6.0.11/spring-jcl-6.0.11.jar:/home/runner/.m2/repository/org/springframework/boot/spring-boot/3.1.2/spring-boot-3.1.2.jar:/home/runner/.m2/repository/org/springframework/spring-expression/6.0.11/spring-expression-6.0.11.jar:/home/runner/.m2/repository/org/springframework/spring-aop/6.0.11/spring-aop-6.0.11.jar
-m
org.example.Main
-pp
-ap
-scope
REACHABLE
-a
pta=handle-invokedynamic:true;cs:2-type;implicit-entries:false;dump:false;reflection-inference:solar;only-app:false;merge-string-objects:false;distinguish-string-constants:all
-a
cg=dump-call-edges:true

**Comment by zhangt2333** [comment]
Try to troubleshoot it gradually from simple analysis options to time-consuming analysis options.

Notes that `cs:2-type;`, `merge-string-objects:false;`, `distinguish-string-constants:all` and `reflection-inference:solar;` are time-consuming. You can observe the analysis time from enabling one to enabling multiple above options to choose the analysis option that best suits your scenario.

**Comment by zhangt2333** [comment]
If no further information is provided, we tend to close this issue.
