### ISSUE TITLE
Context Sensitivity without Contexts (CUT-SHORTCUT)

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#62]
Hello,
I came across this paper:
https://dl.acm.org/doi/pdf/10.1145/3591242, that presents better performance regarding analysis times, so wanted to ask whether there is a certain time line for implementing this?

I also saw in the paper there is available artifact for download but its forked from a very non up to date master branch:
https://doi.org/10.5281/zenodo.7808384

**Comment by silverbullettt** [comment]
We do have intentions to re-implement cut-shortcut on top of the latest Tai-e. However, we cannot provide a specific timeline for its completion due to our busy schedule...
