### ISSUE TITLE
A question about C++ language support

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#65]
Hello everyone, I think `Tai-e` is a very practical tool, and I want to express my gratitude for developing the `Tai-e` platform. I would like to know if you are considering supporting the C++ language (based on LLVM) in the future? Could you recommend a currently user-friendly C++ static analysis tool? Thank you very much!

**Comment by silverbullettt** [comment]
Thank you for your kind words. Supporting C++ (even based on LLVM) is far from trivial, and currently not part of our roadmap. You might want to explore [SVF](https://github.com/SVF-tools/SVF), a well-known C++ static analysis tool.

**Comment by anabioticsoul** [comment]
OK. I am presently engaged in research and learning about SVF tools. I really appreciate your assistance!
