### ISSUE TITLE
Replacing / manipulating IR of methods in "world"

### ISSUE THREAD

**Issue by staslath** [pascal-lab/Tai-e#67]
# Does tai-e support manipulating/replacing the IR of a method that has already been included in the `World`?

## Motivating Use Case
Consider the [Service Loader java API](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html), suppose we have a service called `SearchEngine`, with 2 implementations: 
* `YahooSearchEngine`
*  `BingSearchEngine`

Client code could say:
```java
var results =
  ServiceLoader.load(SearchEngine.class).stream()
    .map(ServiceLoader.Provider::get)
    .map(searchEngine -> searchEngine.search("cat"))
    .toList();
```

and Java's `ServiceLoader` infrastructure would then go and search the `META-INF/services/` directories in the classpath jars to find implementors.

For example, one jar could have a file `META-INF/services/mypkg.SearchEngine` with the following text line:
```
mypkg.YahooSearchEngine
```
and another:
```
mypkg.BingSearchEngine
```
Since implementing classes are read from files, tai-e won't know about them, which compromises call graph construction for example.

I'd love to have your perspective on what would be the tai-e idiomatic way to address this issue.

A naive approach would seek to "rewrite":
```java
ServiceLoader.load(SearchEngine.class).stream()
```
to something like the following (since we know `mypkg.YahooSearchEngine/BingSearchEngine` are the service providers):
```java
Stream.of(
   mypkg.YahooSearchEngine.class.newInstance(), 
   mypkg.BingSearchEngine.class.newInstance()
)
```

while this naive approach is very naive (e.g, it even ignores the fact `ServiceLoader#stream` returns `Stream<Provider<S>>` rather than `Stream<S>` where `S` is the type of the implementing class), hopefully it gets the idea across.

My initial experiments to have a plugin that does that have failed :)
1. When I use `solver.addStmts(...)` to add a set of generated statements mimicking the above appraoche, they do not result in `YahooSearchEngine#search` or `BingSearchEngine#search` being added to the call graph.
2. As a sanity check, if I write the equivalent java code directly (as opposed to IR manipulations) and have it analysed by tai-e, it's capable of "following through the stream.of", and the call graph includes both `YahooSearchEngine#search` and `BingSearchEngine#search`.

Looking forward to your reply!

**Comment by silverbullettt** [comment]
Firstly, Tai-e can indeed simulate the behavior of certain APIs by synthesizing IR in pointer analysis. An example is [ArrayModel](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/analysis/pta/plugin/natives/ArrayModel.java), which we use to model `System.arraycopy()`.

However, for your particular case, a more idiomatic and straightforward approach should be to handle reflection properly. I'm not familiar with `ServiceLoader`, but it seems to create instances (such as your various `*SearchEngine` instances) through reflection. So, the simplest way would be to make Tai-e capable of analyzing the reflection calls within `ServiceLoader`.

There are two ways to address this issue:
1. Use Tai-e's solar (option: `pta=...;reflection-inference:solar;...`), which is a more powerful reflection analysis compared to the default option and may directly resolve instances created by `ServiceLoader`.
2. You can explicitly inform Tai-e through a reflection log. To do this, you need to locate the actual reflection calls in the JDK for `ServiceLoader` (likely `newInstance()` calls), and then use a log to inform Tai-e (option: `pta=...;reflection-log:refl.log;...`). The format of reflection log is the same as [TamiFlex](https://github.com/secure-software-engineering/tamiflex/wiki/Usage#format-of-the-reflection-log-file). For reference, you can take a look at how `refl.log` is written in [java-benchmarks](https://github.com/pascal-lab/java-benchmarks/tree/master/dacapo-2006).

**Comment by zhangt2333** [comment]
> 1. When I use `solver.addStmts(...)` to add a set of generated statements mimicking the above appraoche, they do not result in `YahooSearchEngine#search` or `BingSearchEngine#search` being added to the call graph.

How did you do that (`I use solver.addStmts(...) to add a set of generated statements mimicking the above appraoche`)?

Compared with the generic solution mentioned by @silverbullettt, this requires very careful modeling; you might also consider whether the modeling is wrong.

**Comment by zhangt2333** [comment]
> if there was a good way to access an enclosing class' members inside an InvokeHandler of its non-static inner class?

I do not understand clearly, could you provide an example?

**Comment by zhangt2333** [comment]
In the method `readFile`, you can obtain the InstanceField (Pointer) `fileName` by the `thisObj` (`recvObj`) of `readFile` and the JField `fileName`. Then you can retrieve the PTS of `filenName`.
