### ISSUE TITLE
Does the warning `Cannot resolve ...` affect CFG?

### ISSUE THREAD

**Issue by zhzhdoai** [pascal-lab/Tai-e#8]
### Describe the bug

When "Cannot resolve xxx ", Does it continue to make the complete CFG?
（some edges are missing）

### Tai-e arguments

--allow-phantom -pp -cp PROJECT_CLASSPATH -m PROJECT_CLASS -a icfg -scope APP

**Comment by zhangt2333** [comment]
> When "Cannot resolve xxx ", Does it continue to make the complete CFG?（some edges are missing）

If the unresolved class affects the CG, the CFG is possible to be incomplete.

It is recommended that the scope be changed to `REACHABLE` but not `APP` if you focus more on CFG.

**Comment by zhzhdoai** [comment]
Thanks.
