### ISSUE TITLE
InterTaint transfer and invoke issues in Taint Analysis

### ISSUE THREAD

**Issue by hillwangsec** [pascal-lab/Tai-e#80]
### Description

Hi, 
When I was testing the taint propagation analysis plugin, I found two problems or doubts about the inter-process analysis. But I'm not sure if the framework could be optimized for them.
Thanks!

**The first case** 
is in interface implicit invoke in spring boot controller-service framework which is commonly used i think.
The test case is SSRF in java-sec-code benchmark, could see detail code in below:  
https://github.com/JoyChou93/java-sec-code/blob/master/src/main/java/org/joychou/controller/SSRF.java
in function RestTemplateUrlBanRedirects and RestTemplateUrl.
```
@GetMapping("/restTemplate/vuln1")
    public String RestTemplateUrlBanRedirects(String url){
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON_UTF8);
        return httpService.RequestHttpBanRedirects(url, headers);
    }


    @GetMapping("/restTemplate/vuln2")
    public String RestTemplateUrl(String url){
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON_UTF8);
        return httpService.RequestHttp(url, headers);
    }
```

Because private field variable **httpService** is interface, not initialize an object here **(instead of @resource)** and implicit invoke the method in the impl class  impl/HttpServiceImpl.java.
My test result is our engine and taint analysis plugin could not detect these two vulnerabilities due to tai-e could not identify the call edge? 

However, when i modify the test cases by manually adding initialization of the variable httpService, 
it work!
```
@GetMapping("/restTemplate/vuln2")
    public String RestTemplateUrl(String url){
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON_UTF8);
        httpService = new HttpServiceImpl();  // add the line manually
        return httpService.RequestHttp(url, headers);
    }
```

So, i think here maybe some feature could be optimized?

**The second case** 
in Tai-e test cases provided in:
https://github.com/pascal-lab/Tai-e/blob/master/src/test/resources/pta/taint/InterTaintTransfer.java
the excepted results is 3 vulnerabilities should be detected, but in my testing 9 vulnerabilities detected due to the variable mapping / transfer in inter taint.

> [Pointer analysis] elapsed time: 0.05s
> Detected 9 taint flow(s):
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[0@L4] $r0 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[6@L8] invokestatic SourceSink.sink($r4)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[0@L4] $r0 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[8@L9] invokestatic SourceSink.sink($r5)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[0@L4] $r0 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[10@L10] invokestatic SourceSink.sink($r6)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[1@L5] $r1 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[6@L8] invokestatic SourceSink.sink($r4)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[1@L5] $r1 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[8@L9] invokestatic SourceSink.sink($r5)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[1@L5] $r1 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[10@L10] invokestatic SourceSink.sink($r6)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[2@L6] $r2 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[6@L8] invokestatic SourceSink.sink($r4)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[2@L6] $r2 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[8@L9] invokestatic SourceSink.sink($r5)/0}
> TaintFlow{<InterTaintTransfer: void main(java.lang.String[])>[2@L6] $r2 = invokestatic SourceSink.source()/result -> <InterTaintTransfer: void main(java.lang.String[])>[10@L10] invokestatic SourceSink.sink($r6)/0}

Many wrong results are logged.

**Environment**
> MacOs
> IDEA
> Ta-e version：master branch, commit id: 4c6b337c92e9122051c80cd58028f07816ad9e1e（Commits on Dec 29, 2023）

Thank you very much for your attention and if you have any questions please feel free to let me know!

**Comment by zhangt2333** [comment]
> **The first case** 
> ...
> Because private field variable **httpService** is interface, not initialize an object here **(instead of @resource)** and implicit invoke the method in the impl class impl/HttpServiceImpl.java. 

There may be a related issue for for your reference: #19 . To handle this scenario, some modifications may be necessary, e.g., add a mocked obj (instance of `HttpServiceImpl`) into the `httpService`'s Instance Field Pointer.


> **The second case** in Tai-e test cases provided in: https://github.com/pascal-lab/Tai-e/blob/master/src/test/resources/pta/taint/InterTaintTransfer.java the excepted results is 3 vulnerabilities should be detected, but in my testing 9 vulnerabilities detected due to the variable mapping / transfer in inter taint.
> ...
> Many wrong results are logged.

`2-call` context sensitivity is required to execute this test case to detect 3 taint flow.

https://github.com/pascal-lab/Tai-e/blob/99501551b49b1fd2f2904bf43fd13c727e16c9cf/src/test/java/pascal/taie/analysis/pta/TaintTest.java#L53

https://github.com/pascal-lab/Tai-e/blob/99501551b49b1fd2f2904bf43fd13c727e16c9cf/src/test/resources/pta/taint/InterTaintTransfer-pta-expected.txt#L37-L40
