### ISSUE TITLE
More example?

### ISSUE THREAD

**Issue by SEC-fsq** [pascal-lab/Tai-e#82]
### Clear and concise description of the problem

在测试污点分析时各种报错，希望两位老师给一些完整的例子或代码demo

### Intention to submit PR

No

**Comment by zhangt2333** [comment]
This is your second issue.

Thanks for writing this issue in Chinese, it makes it very easy for a few of us developers to read. However, Tai-e is a project with an international focus, and we aim to keep our community discussions in as widely accessible a language as possible, which is English. This helps us share our open-source progress with interested individuals from all over the world. Kindly consider using English for communication in the future. We appreciate your understanding. Thank you.

---

More information is required to answer your question, e.g., 

- what does the error look like?
- what have you done to try to solve this problem?
- how can we reproduce the same problem as you to help?
- ...

Then we know how we can help you.

Besides, kindly consider using English for communication next time. We appreciate your understanding. Thank you.
