### ISSUE TITLE
What is the support for Java source code? After testing, it was found that some classes did not recognize the method. What are the conditions for Java source code analysis?

### ISSUE THREAD

**Issue by SEC-fsq** [pascal-lab/Tai-e#85]
### Clear and concise description of the problem

What is the support for Java source code? After testing, it was found that some classes did not recognize the method. What are the conditions for Java source code analysis?

### Intention to submit PR

No

**Comment by zhangt2333** [comment]
According to https://tai-e.pascal-lab.net/docs/current/reference/en/command-line-options.html#program-options:

> Currently, Tai-e leverages Soot frontend to parse Java programs and help build Tai-e’s IR. Soot contains two frontends, one for parsing Java source files (.java) and the other one for bytecode files (.class). The former is outdated (only partially supports Java versions up to 7); while the latter, though quite robust (works properly for the .class files compiled by up to Java 17), cannot fully satisfy our requirements. Hence, we plan to develop our own frontend for Tai-e to address the above issues. For now, we advice using Tai-e to analyze bytecode, instead of source code, if possible.
