### ISSUE TITLE
Can we find the source point through annotations? For example, I would like to use the parameter of the method with RequestMapping annotation as the source point

### ISSUE THREAD

**Issue by SEC-fsq** [pascal-lab/Tai-e#87]
### Clear and concise description of the problem

Can we find the source point through annotations? For example, I would like to use the parameter of the method with RequestMapping annotation as the source point

### Intention to submit PR

No

**Comment by zhangt2333** [comment]
Unfortunately, there is currently no direct support. Current workaround is to implement the [Plugin](https://github.com/pascal-lab/Tai-e/blob/master/src/main/java/pascal/taie/analysis/pta/plugin/Plugin.java) or modify Tai-e's source code to achieve a high level of customization.

**Comment by zhangt2333** [comment]
The taint rules with programmatic configuration support are now available in [v0.5.1](https://github.com/pascal-lab/Tai-e/releases/tag/v0.5.1). 

It allows you to scan the annotations in the IR for elements annotated with `@RequestMapping` and create taint rules for them without having to predefine the taint analysis rules in config files.

For details on usages, please refer to our [documentation on programmatic taint configuration](https://tai-e.pascal-lab.net/docs/0.5.1/reference/en/taint-analysis.html#programmatic-taint-configuration-provider).
