### ISSUE TITLE
How could I build a more complete ICFG?

### ISSUE THREAD

**Issue by anabioticsoul** [pascal-lab/Tai-e#9]
Hello everyone. I have a question about building ICFG. WALA has a class `AllApplicationEntrypoints` that Call Graph can be constructed more accurately with all application entrypoints. But in Tai-e, it seems like the main class should only be specified as a single entrypoint with the option `-m`.

**Comment by zhangt2333** [comment]
> it seems like the main class should only be specified as a single entrypoint with the option -m.

As we discussed, there is only one main method in general that in general Java program (so `-m` is an alias of `--main-class` but not `--main-classes` in Tai-e options). But in other scenarios, multiple entrypoints may be required, e.g., JUnit test entries.

If you want to add multiple entrypoints in Tai-e, refer to the class `pascal.taie.analysis.pta.core.solver.EntryPoint` and method `pascal.taie.analysis.pta.core.solver.Solver#addEntryPoint` (you can call it in the plugin you wrote).

Some usage:
* https://github.com/pascal-lab/Tai-e/blob/d9784e3/src/main/java/pascal/taie/analysis/pta/plugin/EntryPointHandler.java#L60-L61
* https://github.com/pascal-lab/Tai-e/blob/d9784e3/src/main/java/pascal/taie/analysis/pta/plugin/ThreadHandler.java#L124-L129

**Comment by anabioticsoul** [comment]
> If you want to add multiple entrypoints (which will also be the entries of call graph and ICFG) in Tai-e, refer to the class `pascal.taie.analysis.pta.core.solver.EntryPoint` and method `pascal.taie.analysis.pta.core.solver.Solver#addEntryPoint` (you can call it in the [plugin](https://github.com/pascal-lab/Tai-e/wiki/Pointer-Analysis-Framework#analysis-plugin-system) you write).

I successfully add all entrypoints I want through my plugin, but every single pointer analysis takes a really long time. Thanks a lot!
