### ISSUE TITLE
How to handle java generics feature in taint analysis.

### ISSUE THREAD

**Issue by Spr1n9T1me** [pascal-lab/Tai-e#91]
### Description

How should I handle java generics feature in taint analysis?
For example, if I want to use the `extract()` method below as the sink method, how should I write in taint-config.yml?
```java
    public E extract(Object oTarget) {
        ValueExtractor[] aExtractor = this.getExtractors();
        int i = 0;
        for(int c = aExtractor.length; i < c && oTarget != null; ++i) {
           //...
        }
        
```
The return type of `extract()` is Java Generics `E`, and relevant content in taint-config.yml might be like:
```yaml
sinks:
  - { method: "<com.tangosol.util.extractorChainedExtractor: E extract(java.lang.Object)>", index: 0 }
```
Is it reasonable for `E` or we have some solutions for it ?

**Comment by zhangt2333** [comment]
As a result of generalized erasure, you can use `<com.tangosol.util.extractorChainedExtractor: java.lang.Object extract(java.lang.Object)>` instead.

**Comment by Spr1n9T1me** [comment]
I got it,thx!😊

**Comment by Spr1n9T1me** [comment]
It works! THX.
